<a href="https://colab.research.google.com/github/madhucherr/main/blob/main/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importng the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__


'2.9.2'

# Part1 data preprocessing

Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


Encoding the categorical data
label encoding the"gender

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


OneHotEncoding the"geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splittinig the dataset into the training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.2,random_state = 0)

feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test  = sc.transform(x_test)

#Part2 Building the ANN

Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6,activation ="relu"))

Adding the scond hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6,activation ="relu"))

adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1,activation ="sigmoid"))

#Part3 Treainning the ANN

Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

training the ANN on the training set

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5890 - accuracy: 0.6977
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4747 - accuracy: 0.7965
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4491 - accuracy: 0.8014
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4356 - accuracy: 0.8080
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4282 - accuracy: 0.8108
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4232 - accuracy: 0.8166
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4186 - accuracy: 0.8202
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4146 - accuracy: 0.8226
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4112 - accuracy: 0.8270
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4079 - accura

#part4 Making the predictions And evaluating the models

Predicting the result of singlke observation

In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 318ms/step
[[False]]


predicting the test set results

In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[1 0]
 [1 1]
 [1 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


Making the confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 574 1021]
 [ 107  298]]


0.436