<a href="https://colab.research.google.com/github/madhucherr/main/blob/main/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing the libraies

In [ ]:
import numpy as np
import pandas as pd

importing dataset

In [ ]:
DA=pd.read_csv('Data.csv')
x=DA.iloc[:,: -1].values
y=DA.iloc[:,-1].values
print(x)
print()
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


filling the missing values

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform (x[:,1:3])
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding independent values

In [ ]:
from sklearn .compose import ColumnTransformer
from sklearn .preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoders',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


encoding dependent variables

In [ ]:
from sklearn .preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


splitting the data into test and train set

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)


feature scaling 

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain[:,3:] = sc.fit_transform(xtrain[:,3:])
xtest[:,3:] = sc.transform(xtest[:,3:])
print(xtrain)
print(xtest)

[[-0.7745966692414834 -0.5773502691896258 1.2909944487358056
  -0.19159184384578545 -1.0781259408412425]
 [-0.7745966692414834 1.7320508075688774 -0.7745966692414834
  -0.014117293757057777 -0.07013167641635372]
 [1.2909944487358056 -0.5773502691896258 -0.7745966692414834
  0.566708506533324 0.633562432710455]
 [-0.7745966692414834 -0.5773502691896258 1.2909944487358056
  -0.30453019390224867 -0.30786617274297867]
 [-0.7745966692414834 -0.5773502691896258 1.2909944487358056
  -1.9018011447007988 -1.420463615551582]
 [1.2909944487358056 -0.5773502691896258 -0.7745966692414834
  1.1475343068237058 1.232653363453549]
 [-0.7745966692414834 1.7320508075688774 -0.7745966692414834
  1.4379472069688968 1.5749910381638885]
 [1.2909944487358056 -0.5773502691896258 -0.7745966692414834
  -0.7401495441200351 -0.5646194287757332]]
[[-0.7745966692414834 1.7320508075688774 -0.7745966692414834
  -1.4661817944830124 -0.9069571034860727]
 [1.2909944487358056 -0.5773502691896258 -0.7745966692414834
  -0.4