<a href="https://colab.research.google.com/github/madhucherr/main/blob/main/linear_algebra_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing and creating martrix

In [ ]:
import numpy as np
import numpy.linalg as la

a=np.array([[1,2,3],
            [3,4,5],
            [6,7,8]])
b=np.array([[2,3,4],
            [5,7,6],
            [5,9,7]])
print("A =",a)
print("B =",b)

A = [[1 2 3]
 [3 4 5]
 [6 7 8]]
B = [[2 3 4]
 [5 7 6]
 [5 9 7]]


matrix operations

In [ ]:
c=a+b
d=a-b
print("A+B =",c)
print("A-B =",d)

A+B = [[ 3  5  7]
 [ 8 11 11]
 [11 16 15]]
A-B = [[-1 -1 -1]
 [-2 -3 -1]
 [ 1 -2  1]]


multiplication

In [ ]:
c=a.dot(b)
print(c)
print()
c1=np.dot(a,b)
print(c1)
print()
d=np.matmul(a,b)
print(d)

[[ 27  44  37]
 [ 51  82  71]
 [ 87 139 122]]

[[ 27  44  37]
 [ 51  82  71]
 [ 87 139 122]]

[[ 27  44  37]
 [ 51  82  71]
 [ 87 139 122]]


transpose

In [ ]:
a1=np.array([[1,2,3],
            [3,4,5],
            [6,7,8]])
print(a1)
print()
tran=np.transpose(a1)
print(tran)

[[1 2 3]
 [3 4 5]
 [6 7 8]]

[[1 3 6]
 [2 4 7]
 [3 5 8]]


determinate

In [ ]:
a2=np.array([[1,2,3],
            [3,4,5],
            [6,7,8]])
d=la.det(a2)
print(d)
b=np.array([[2,3,4],
            [5,7,6],
            [5,9,7]])
d1=la.det(b)
print(d1)

0.0
14.999999999999993


inerverse

In [ ]:
a3=np.array([[1,2],
            [3,4]])
g =la.inv(a3)
print(g)
b=np.array([[2,3,4],
            [5,7,6],
            [5,9,7]])
d1=la.inv(b)
print(d1)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-0.33333333  1.         -0.66666667]
 [-0.33333333 -0.4         0.53333333]
 [ 0.66666667 -0.2        -0.06666667]]


eigen

In [ ]:
a=np.array([[1,2,3],
            [3,4,5],
            [6,7,8]])
ae=la.eig(a)
ae, v=la.eig(a)
print(ae)
print()
print(v)

[ 1.40663730e+01 -1.06637298e+00  3.43927949e-17]

[[ 0.26564776  0.74442863  0.40824829]
 [ 0.49120712  0.19070122 -0.81649658]
 [ 0.82954616 -0.63988988  0.40824829]]


Solving linear equation

In [ ]:
A=np.array([[1,2],
            [3,4]])
b=np.array([[5],
            [6]])

Ainv=la.inv(A)
x=Ainv.dot(b)
print(x)

[[-4. ]
 [ 4.5]]
